services:
  - type: web
    name: opshk
    env: python
    plan: free
    buildCommand: |
      rm -rf .venv  # Очищаем старое окружение
      python3.9 -m venv .venv  # Создаём новое
      .venv/bin/python3.9 -m pip install --upgrade pip  # Обновляем pip
      .venv/bin/pip install --no-cache-dir -r requirements.txt  # Устанавливаем без кэша
    startCommand: "python trainer/main.py"
    repo: https://github.com/APavlikV/OPSHK
    branch: main
