services:
  - type: web
    name: opshk-bot-dev
    env: python
    repo: https://github.com/APavlikV/OPSHK
    branch: dev
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python trainer/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: TELEGRAM_TOKEN
        sync: false
      - key: RENDER_API_KEY
        sync: false
      - key: PORT
        value: 10001
      - key: DB_HOST
        value: pg-456.oregon-postgres.render.com
      - key: DB_NAME
        value: opshk
      - key: DB_USER
        value: opshk_user
      - key: DB_PASS
        sync: false
      - key: REDIS_HOST
        value: red-cvud.oregon-redis.render.com
      - key: REDIS_PORT
        value: 6379
