services:
  - type: web
    name: opshk-bot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python trainer/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: TELEGRAM_TOKEN
        sync: false
      - key: RENDER_API_KEY
        sync: false
      - key: PORT
        value: 10000
