services:
  - type: web
    name: opshk
    env: python
    plan: free
    buildCommand: |
      rm -rf .venv  # Удаляем старое окружение, чтобы избежать кэша
      python3.9 -m venv .venv  # Создаём новое окружение
      .venv/bin/python3.9 -m pip install --upgrade pip  # Обновляем pip
      .venv/bin/pip install -r requirements.txt  # Устанавливаем зависимости
    startCommand: "python main.py"
    repo: https://github.com/APavlikV/OPSHK
    branch: main
