services:
  - type: web
    name: opshk-bot
    env: python
    python_version: 3.11  # Или твоя версия
    buildCommand: pip install -r requirements.txt
    startCommand: python trainer/main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: RENDER_API_KEY
        sync: false
