services:
  - type: web
    name: opshk-bot
    env: python
    python_version: 3.11
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python trainer/main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: RENDER_API_KEY
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
